# Generated by Django 5.0.6 on 2024-07-08 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('electionid', models.IntegerField(primary_key=True, serialize=False)),
                ('year', models.DateField(default=2024)),
                ('num_offices', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('voterid', models.IntegerField(primary_key=True, serialize=False)),
                ('auth', models.SmallIntegerField(default=0)),
                ('pub_key', models.BinaryField()),
                ('priv_key', models.BinaryField()),
                ('nonce', models.BinaryField()),
                ('hash', models.BinaryField()),
                ('salt', models.BinaryField()),
                ('electionid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='election', to='api.election')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('voterid', 'electionid')},
            },
        ),
    ]
