# Generated by Django 5.0.6 on 2024-06-20 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='voter',
            old_name='electionid',
            new_name='election',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='hash',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='name',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='nonce',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='priv_key',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='pub_key',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='salt',
        ),
        migrations.AddField(
            model_name='voter',
            name='voter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voter', to=settings.AUTH_USER_MODEL),
        ),
    ]
