# Generated by Django 5.0.6 on 2024-07-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_voter_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='name',
            field=models.TextField(default=' '),
        ),
    ]
