# Generated by Django 5.0.6 on 2024-07-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_voter_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='year',
            field=models.IntegerField(default=2024),
        ),
    ]
