# Generated by Django 5.0.6 on 2024-07-14 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_offices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='pub_key',
            field=models.TextField(),
        ),
    ]
