# Generated by Django 5.0.6 on 2024-07-16 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_voter_pub_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voter',
            name='voterid',
            field=models.IntegerField(),
        ),
    ]
