# Generated by Django 5.1.2 on 2024-12-18 04:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='END_ELECTION',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 18, 4, 42, 0, 824942)),
        ),
        migrations.AddField(
            model_name='election',
            name='END_SETTING',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 18, 4, 42, 0, 824924)),
        ),
    ]
