# Generated by Django 5.1.2 on 2025-01-03 21:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_election_end_election_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='AUTH',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='voter',
            name='CANDIDATE',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='election',
            name='END_ELECTION',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 3, 21, 23, 26, 230220, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='election',
            name='END_SETTING',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 3, 21, 23, 26, 230182, tzinfo=datetime.timezone.utc)),
        ),
    ]
