# Generated by Django 5.1.2 on 2025-02-05 03:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_remove_election_num_offices_remove_election_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='END_ELECTION',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 5, 3, 34, 27, 626909, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='election',
            name='END_SETTING',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 5, 3, 34, 27, 626868, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='voter',
            name='NAME',
            field=models.TextField(),
        ),
    ]
