# Generated by Django 5.1.2 on 2024-12-06 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ELECTION',
            fields=[
                ('ELECTIONID', models.IntegerField(primary_key=True, serialize=False)),
                ('YEAR', models.IntegerField(default=2024)),
                ('NUM_OFFICES', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OFFICE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.TextField(default=' ')),
                ('DIGIT_NUM', models.IntegerField()),
                ('ELECTIONID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.election')),
            ],
            options={
                'unique_together': {('NAME', 'ELECTIONID')},
            },
        ),
        migrations.CreateModel(
            name='VOTER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.TextField(default=' ')),
                ('CPF', models.TextField()),
                ('PUB_KEY', models.TextField(default=' ')),
                ('PRIV_KEY', models.BinaryField()),
                ('SALT', models.BinaryField()),
                ('ELECTIONID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.election')),
            ],
            options={
                'unique_together': {('CPF', 'ELECTIONID')},
            },
        ),
    ]
