# Generated by Django 5.1.2 on 2025-01-03 13:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_election_end_election_election_end_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='END_ELECTION',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 3, 13, 32, 19, 849735, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='election',
            name='END_SETTING',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 3, 13, 32, 19, 849695, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='election',
            name='YEAR',
            field=models.IntegerField(default=2025),
        ),
    ]
