# Generated by Django 5.0.6 on 2024-06-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=11)),
                ('electionid', models.CharField(max_length=3)),
                ('pub_key', models.BinaryField()),
                ('priv_key', models.BinaryField()),
                ('nonce', models.BinaryField()),
                ('hash', models.BinaryField()),
                ('salt', models.BinaryField()),
            ],
        ),
    ]
