CREATE TABLE ELECTION (
    ID INT PRIMARY KEY NOT NULL,
    ANO INT
);

CREATE TABLE VOTERS(
    NAME TEXT,
    CPF INT NOT NULL,
    ID INT NOT NULL REFERENCES ELECTION(ID),
    AUTHENTICATED BINARY(1),
    CANDIDATE BINARY(1),
    PRIMARY KEY (CPF,ID)
);

CREATE TABLE CANDIDATES(
    CPF INT NOT NULL REFERENCES VOTER(CPF),
    ID INT NOT NULL REFERENCES ELECTION(ID),
    OFFICE TEXT,
    CAMPAIGNID INT,
    PRIMARY KEY (CPF,ID)
);

CREATE TABLE OFFICES(
    NAME VARCHAR(50) NOT NULL,
    ID INT NOT NULL REFERENCES ELECTION(ID),
    DIGIT_NUM INT,
    PRIMARY KEY (NAME, ID)
);